"use client";
import{FormEvent,useEffect,useMemo,useState}from"react";
import{goals,gym,visualAssets,type GoalId}from"@/lib/gym";
const zones=[
{id:"01",name:"STRENGTH",title:"Train with intent.",text:"Your main floor for resistance, progression and consistency.",image:visualAssets.hero},
{id:"02",name:"CONDITIONING",title:"Build your engine.",text:"A dedicated route for movement, stamina and work capacity.",image:visualAssets.cardio},
{id:"03",name:"THE EXPERIENCE",title:"Make showing up easy.",text:"A focused local training environment in the heart of Bettiah.",image:visualAssets.training}];
function track(name:string,detail?:Record<string,string>){try{void fetch("/api/events",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,...detail}),keepalive:true})}catch{}}
export default function Home(){
const[goal,setGoal]=useState<GoalId>("muscle"),[activeZone,setActiveZone]=useState(zones[0]),[formState,setFormState]=useState<"idle"|"sending"|"sent"|"error">("idle"),[formMessage,setFormMessage]=useState(""),[menuOpen,setMenuOpen]=useState(false);
useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting&&entry.target.classList.add("is-visible")),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));return()=>observer.disconnect()},[]);
const selectedGoal=useMemo(()=>goals.find(item=>item.id===goal)??goals[0],[goal]);
async function submitLead(event:FormEvent<HTMLFormElement>){event.preventDefault();setFormState("sending");const form=new FormData(event.currentTarget);try{const response=await fetch("/api/leads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:String(form.get("name")??""),phone:String(form.get("phone")??""),goal,preferredTime:String(form.get("preferredTime")??""),source:"kingdom-gym-website"})});const result=await response.json();if(!response.ok)throw new Error(result.message||"Unable to send");setFormState("sent");setFormMessage("Request received. The gym can contact you about your visit.");track("trial_submit",{goal});event.currentTarget.reset()}catch{setFormState("error");setFormMessage("Something went wrong. Call the gym directly at +91 70049 04254.")}}
return <main>
<header className="nav"><a className="brand" href="#top">KINGDOM<span>.</span></a><button className="menu-button" type="button" onClick={()=>setMenuOpen(v=>!v)} aria-expanded={menuOpen}><span/><span/><span/></button><nav className={menuOpen?"nav-links open":"nav-links"}><a href="#experience" onClick={()=>setMenuOpen(false)}>Experience</a><a href="#goals" onClick={()=>setMenuOpen(false)}>Goals</a><a href="#journey" onClick={()=>setMenuOpen(false)}>Journey</a><a href="#visit" onClick={()=>setMenuOpen(false)}>Visit</a></nav><a className="nav-cta" href="#visit" onClick={()=>track("nav_trial_click")}>START YOUR VISIT <span>↗</span></a></header>
<section id="top" className="hero"><div className="hero-media" style={{backgroundImage:`url(${visualAssets.hero})`}}/><div className="hero-grain"/><div className="hero-content"><p className="eyebrow">BETTIAH · BASANT VIHAR · HARIWATIKA CHOWK</p><h1>TRAIN<br/><em>DIFFERENT.</em></h1><p className="hero-copy">A focused place to build strength, improve fitness and make training part of your identity.</p><div className="hero-actions"><a className="button button-solid" href="#visit" onClick={()=>track("hero_trial_click")}>START YOUR VISIT <span>↗</span></a><a className="button button-ghost" href="#experience" onClick={()=>track("hero_explore_click")}>EXPLORE THE GYM <span>↓</span></a></div></div><div className="hero-meta"><span>OPEN DAILY</span><strong>{gym.hours}</strong><span>GOOGLE</span><strong>{gym.rating} / 5 · {gym.reviewCount} reviews</strong></div><a className="scroll-cue" href="#experience">SCROLL TO EXPLORE <span>↓</span></a></section>
<section className="ticker"><div>STRENGTH</div><div>CONSISTENCY</div><div>DISCIPLINE</div><div>PROGRESS</div><div>BETTIAH</div><div>STRENGTH</div><div>CONSISTENCY</div></section>
<section id="experience" className="section experience"><div className="section-head reveal"><div><p className="eyebrow">THE EXPERIENCE</p><h2>DON’T JUST<br/><span>JOIN A GYM.</span></h2></div><p className="section-intro">Explore the experience before you ever walk through the door. Pick a zone, find your reason, then take the next step.</p></div><div className="zone-grid reveal"><div className="zone-list">{zones.map(zone=><button type="button" key={zone.id} className={activeZone.id===zone.id?"zone active":"zone"} onClick={()=>{setActiveZone(zone);track("zone_explore",{zone:zone.name})}}><span>{zone.id}</span><div><b>{zone.name}</b><small>{zone.title}</small></div><i>↗</i></button>)}</div><div className="zone-preview"><img src={activeZone.image} alt={`${activeZone.name} gym visual`}/><div className="zone-overlay"><span>{activeZone.name}</span><h3>{activeZone.title}</h3><p>{activeZone.text}</p></div></div></div></section>
<section id="goals" className="section goals-section"><div className="goal-copy reveal"><p className="eyebrow">FIND YOUR ROUTE</p><h2>WHAT ARE<br/><em>YOU TRAINING FOR?</em></h2><p>Choose the outcome you care about. We’ll turn it into a simple starting point for your first visit.</p></div><div className="goal-explorer reveal"><div className="goal-tabs" role="tablist" aria-label="Training goals">{goals.map(item=><button type="button" key={item.id} className={goal===item.id?"goal-tab active":"goal-tab"} onClick={()=>{setGoal(item.id);track("goal_select",{goal:item.id})}}><span>{item.kicker}</span>{item.label}</button>)}</div><div className="goal-result"><div className="result-number">0{goals.findIndex(item=>item.id===goal)+1}</div><div><p className="eyebrow">YOUR ROUTE</p><h3>{selectedGoal.label}</h3><p>{selectedGoal.copy}</p><a href="#visit" className="text-link" onClick={()=>track("goal_cta_click",{goal})}>BUILD MY FIRST VISIT ↗</a></div></div></div></section>
<section id="journey" className="journey"><div className="journey-image"/><div className="journey-content reveal"><p className="eyebrow">THE FIRST VISIT</p><h2>WALK IN.<br/><span>LOCK IN.</span><br/>LEVEL UP.</h2><div className="steps"><div><span>01</span><b>ARRIVE</b><p>Come to Basant Vihar, Hariwatika Chowk.</p></div><div><span>02</span><b>EXPLORE</b><p>See the space, understand the environment and ask your questions.</p></div><div><span>03</span><b>START</b><p>Choose the training route that fits your goal.</p></div></div></div></section>
<section className="proof section"><div className="proof-card reveal"><p className="eyebrow">LOCAL SIGNAL</p><div className="rating">{gym.rating.toFixed(1)}<span>/5</span></div><p>Publicly listed Google rating</p><strong>{gym.reviewCount} reviews</strong></div><div className="proof-card reveal"><p className="eyebrow">WHEN TO TRAIN</p><div className="rating">05<span>—</span>21</div><p>Publicly listed daily hours</p><strong>{gym.hours}</strong></div><div className="proof-card reveal"><p className="eyebrow">WHERE TO FIND US</p><div className="rating">845<span>438</span></div><p>PIN code</p><strong>Basant Vihar · Hariwatika Chowk</strong></div></section>
<section id="visit" className="visit section"><div className="visit-copy reveal"><p className="eyebrow">YOUR NEXT REP STARTS HERE</p><h2>READY TO<br/><em>EXPERIENCE IT?</em></h2><p>Tell us what you’re working toward. Your request goes to the website’s lead endpoint and can be forwarded to the gym’s chosen CRM/webhook.</p><div className="contact-row"><a href="tel:+917004904254" onClick={()=>track("call_click")}>CALL {gym.phone} ↗</a><a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(gym.mapsQuery)}`} onClick={()=>track("maps_click")}>GET DIRECTIONS ↗</a></div></div><form className="lead-form reveal" onSubmit={submitLead}><label>YOUR NAME<input name="name" placeholder="Aman Kumar" required minLength={2}/></label><label>PHONE<input name="phone" placeholder="+91 98765 43210" inputMode="tel" required/></label><label>WHEN DO YOU PREFER TO VISIT?<select name="preferredTime" defaultValue=""><option value="">Choose a time</option><option>Morning · 5–9 AM</option><option>Day · 9 AM–5 PM</option><option>Evening · 5–9 PM</option></select></label><input type="hidden" name="goal" value={goal}/><button className="button button-solid form-submit" type="submit" disabled={formState==="sending"}>{formState==="sending"?"SENDING…":formState==="sent"?"REQUEST RECEIVED ✓":"REQUEST A VISIT ↗"}</button><p className="form-note" aria-live="polite">{formMessage||"No payment is taken here. This is a visit enquiry."}</p></form></section>
<footer className="footer"><div><a className="brand" href="#top">KINGDOM<span>.</span></a><p>Train different. Bettiah, Bihar.</p></div><div><p>{gym.address}</p><p>{gym.hours}</p></div><div><a href="tel:+917004904254">{gym.phone}</a><a href="#top">BACK TO TOP ↑</a></div></footer><a className="mobile-cta" href="#visit" onClick={()=>track("mobile_trial_click")}>START YOUR VISIT <span>↗</span></a>
</main>}